# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clJwpWe1fl1KfjIATiv1JGuC1CmJ-wz-
"""

import pandas as pd
baza={
    "FISH":[ "Aliyeva Ra'no" , 'Valiyev Vali' , 'Aliyev Ali' , "Ma'rifova Muslimabonu" , 'Ikromova Dilnavoz' , 'Ahmadjonov Aziz' ,  'Qurbonova Madina' , 'Mahmudov Said' , 'Sobirov Hamdam' , 'Qurbonov Abror' ],
    "Yoshi":[ '11' , '15', '10' , '18' , '19' , '9' , '12' , '14' , '13' , '16' ,    ],
    "Maktabi":[ '3-maktab' , 'Prezident maktabi' , '1-IDUM' , '17-maktab' , '19-maktab' , '1-maktab' , '44-maktab' , 'ixtisoslashtirilgan musiqa maktabi' , '10-maktab' , '2-maktab'   ],
    "Jinsi":[  'qiz bola' , "o'g'il bola" , "o'g'il bola" , 'qiz bola' , 'qiz bola' , "o'g'il bola" , 'qiz bola' ,  "o'g'il bola" ,  "o'g'il bola" ,  "o'g'il bola" ,   ],
    "Manzili":[ 'Andijon shahar' , "Farg'ona shahar" , 'Toshloq tuman' , "Qo'qon shahar" , "Marg'ilon sahar" , 'Quva shahar' , 'Toshkent shahar' , 'Furqat tumani' , 'Qirguli shahar' , 'Namangan shahar'  ]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Maktabi']=='Prezident maktabi']
print(filtr)

filtr=db[(db['Maktabi']=='Prezident maktabi') & (db['Jinsi']=="o'g'il bola")]
print(filtr)